# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simian/public/proto/custom_actor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from simian.public.proto import actor_pb2 as simian_dot_public_dot_proto_dot_actor__pb2
from simian.public.proto import motion_model_pb2 as simian_dot_public_dot_proto_dot_motion__model__pb2
from simian.public.proto import planar_pb2 as simian_dot_public_dot_proto_dot_planar__pb2
from simian.public.proto import shape_pb2 as simian_dot_public_dot_proto_dot_shape__pb2
from simian.public.proto import spatial_pb2 as simian_dot_public_dot_proto_dot_spatial__pb2


# @@protoc_insertion_point(post_imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simian/public/proto/custom_actor.proto',
  package='simian_public.custom_actor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&simian/public/proto/custom_actor.proto\x12\x1asimian_public.custom_actor\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fsimian/public/proto/actor.proto\x1a&simian/public/proto/motion_model.proto\x1a simian/public/proto/planar.proto\x1a\x1fsimian/public/proto/shape.proto\x1a!simian/public/proto/spatial.proto\"\xc8\x02\n\x0b\x44\x65scription\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustom_type\x18\x03 \x01(\t\x12>\n\robstacle_type\x18\x04 \x01(\x0e\x32\'.simian_public.actor.Actor.ObstacleType\x12\x34\n\rinitial_state\x18\x05 \x01(\x0b\x32\x1d.simian_public.planar.State2d\x12)\n\x05shape\x18\x06 \x01(\x0b\x32\x1a.simian_public.shape.Shape\x12=\n\x0cmotion_model\x18\x07 \x01(\x0b\x32\'.simian_public.motion_model.Description\x12*\n\nextra_data\x18\x08 \x01(\x0b\x32\x16.google.protobuf.Value\"G\n\nSimToActor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x05state\x18\x02 \x01(\x0b\x32\x1c.simian_public.spatial.State\"N\n\nActorToSim\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\x07\x63ommand\x18\x02 \x01(\x0b\x32!.simian_public.motion_model.Inputb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,simian_dot_public_dot_proto_dot_actor__pb2.DESCRIPTOR,simian_dot_public_dot_proto_dot_motion__model__pb2.DESCRIPTOR,simian_dot_public_dot_proto_dot_planar__pb2.DESCRIPTOR,simian_dot_public_dot_proto_dot_shape__pb2.DESCRIPTOR,simian_dot_public_dot_proto_dot_spatial__pb2.DESCRIPTOR,])




_DESCRIPTION = _descriptor.Descriptor(
  name='Description',
  full_name='simian_public.custom_actor.Description',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='simian_public.custom_actor.Description.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='simian_public.custom_actor.Description.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='custom_type', full_name='simian_public.custom_actor.Description.custom_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obstacle_type', full_name='simian_public.custom_actor.Description.obstacle_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initial_state', full_name='simian_public.custom_actor.Description.initial_state', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='simian_public.custom_actor.Description.shape', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motion_model', full_name='simian_public.custom_actor.Description.motion_model', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_data', full_name='simian_public.custom_actor.Description.extra_data', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=604,
)


_SIMTOACTOR = _descriptor.Descriptor(
  name='SimToActor',
  full_name='simian_public.custom_actor.SimToActor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='simian_public.custom_actor.SimToActor.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='simian_public.custom_actor.SimToActor.state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=606,
  serialized_end=677,
)


_ACTORTOSIM = _descriptor.Descriptor(
  name='ActorToSim',
  full_name='simian_public.custom_actor.ActorToSim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='simian_public.custom_actor.ActorToSim.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='simian_public.custom_actor.ActorToSim.command', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=679,
  serialized_end=757,
)

_DESCRIPTION.fields_by_name['obstacle_type'].enum_type = simian_dot_public_dot_proto_dot_actor__pb2._ACTOR_OBSTACLETYPE
_DESCRIPTION.fields_by_name['initial_state'].message_type = simian_dot_public_dot_proto_dot_planar__pb2._STATE2D
_DESCRIPTION.fields_by_name['shape'].message_type = simian_dot_public_dot_proto_dot_shape__pb2._SHAPE
_DESCRIPTION.fields_by_name['motion_model'].message_type = simian_dot_public_dot_proto_dot_motion__model__pb2._DESCRIPTION
_DESCRIPTION.fields_by_name['extra_data'].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
_SIMTOACTOR.fields_by_name['state'].message_type = simian_dot_public_dot_proto_dot_spatial__pb2._STATE
_ACTORTOSIM.fields_by_name['command'].message_type = simian_dot_public_dot_proto_dot_motion__model__pb2._INPUT
DESCRIPTOR.message_types_by_name['Description'] = _DESCRIPTION
DESCRIPTOR.message_types_by_name['SimToActor'] = _SIMTOACTOR
DESCRIPTOR.message_types_by_name['ActorToSim'] = _ACTORTOSIM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Description = _reflection.GeneratedProtocolMessageType('Description', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPTION,
  '__module__' : 'simian.public.proto.custom_actor_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.custom_actor.Description)
  })
_sym_db.RegisterMessage(Description)

SimToActor = _reflection.GeneratedProtocolMessageType('SimToActor', (_message.Message,), {
  'DESCRIPTOR' : _SIMTOACTOR,
  '__module__' : 'simian.public.proto.custom_actor_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.custom_actor.SimToActor)
  })
_sym_db.RegisterMessage(SimToActor)

ActorToSim = _reflection.GeneratedProtocolMessageType('ActorToSim', (_message.Message,), {
  'DESCRIPTOR' : _ACTORTOSIM,
  '__module__' : 'simian.public.proto.custom_actor_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.custom_actor.ActorToSim)
  })
_sym_db.RegisterMessage(ActorToSim)


# @@protoc_insertion_point(module_scope)
