# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simian/public/proto/stack_logs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


# @@protoc_insertion_point(post_imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simian/public/proto/stack_logs.proto',
  package='simian_public.stack_logs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$simian/public/proto/stack_logs.proto\x12\x18simian_public.stack_logs\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n\x0cStackLogLine\x12\x13\n\x0bsource_file\x18\x01 \x01(\t\x12\x13\n\x0bsource_line\x18\x02 \x01(\x05\x12\x15\n\rsource_module\x18\x03 \x01(\t\x12\x11\n\tthread_id\x18\x04 \x01(\x05\x12\x13\n\x0bthread_name\x18\x05 \x01(\t\x12\x0b\n\x03msg\x18\x06 \x01(\t\x12(\n\x04time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x42\n\tlog_level\x18\x08 \x01(\x0e\x32/.simian_public.stack_logs.StackLogLine.LogLevel\"K\n\x08LogLevel\x12\n\n\x06NOTSET\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\n\x12\x08\n\x04INFO\x10\x14\x12\x08\n\x04WARN\x10\x1e\x12\t\n\x05\x45RROR\x10(\x12\t\n\x05\x46\x41TAL\x10\x32\"A\n\tStackLogs\x12\x34\n\x04line\x18\x01 \x03(\x0b\x32&.simian_public.stack_logs.StackLogLineb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_STACKLOGLINE_LOGLEVEL = _descriptor.EnumDescriptor(
  name='LogLevel',
  full_name='simian_public.stack_logs.StackLogLine.LogLevel',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=1, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=2, number=20,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARN', index=3, number=30,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=40,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FATAL', index=5, number=50,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=344,
  serialized_end=419,
)
_sym_db.RegisterEnumDescriptor(_STACKLOGLINE_LOGLEVEL)


_STACKLOGLINE = _descriptor.Descriptor(
  name='StackLogLine',
  full_name='simian_public.stack_logs.StackLogLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_file', full_name='simian_public.stack_logs.StackLogLine.source_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_line', full_name='simian_public.stack_logs.StackLogLine.source_line', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_module', full_name='simian_public.stack_logs.StackLogLine.source_module', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='simian_public.stack_logs.StackLogLine.thread_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thread_name', full_name='simian_public.stack_logs.StackLogLine.thread_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='simian_public.stack_logs.StackLogLine.msg', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='simian_public.stack_logs.StackLogLine.time', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='log_level', full_name='simian_public.stack_logs.StackLogLine.log_level', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STACKLOGLINE_LOGLEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=419,
)


_STACKLOGS = _descriptor.Descriptor(
  name='StackLogs',
  full_name='simian_public.stack_logs.StackLogs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='simian_public.stack_logs.StackLogs.line', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=486,
)

_STACKLOGLINE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STACKLOGLINE.fields_by_name['log_level'].enum_type = _STACKLOGLINE_LOGLEVEL
_STACKLOGLINE_LOGLEVEL.containing_type = _STACKLOGLINE
_STACKLOGS.fields_by_name['line'].message_type = _STACKLOGLINE
DESCRIPTOR.message_types_by_name['StackLogLine'] = _STACKLOGLINE
DESCRIPTOR.message_types_by_name['StackLogs'] = _STACKLOGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StackLogLine = _reflection.GeneratedProtocolMessageType('StackLogLine', (_message.Message,), {
  'DESCRIPTOR' : _STACKLOGLINE,
  '__module__' : 'simian.public.proto.stack_logs_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.stack_logs.StackLogLine)
  })
_sym_db.RegisterMessage(StackLogLine)

StackLogs = _reflection.GeneratedProtocolMessageType('StackLogs', (_message.Message,), {
  'DESCRIPTOR' : _STACKLOGS,
  '__module__' : 'simian.public.proto.stack_logs_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.stack_logs.StackLogs)
  })
_sym_db.RegisterMessage(StackLogs)


# @@protoc_insertion_point(module_scope)
