# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simian/public/proto/transfer_function.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




# @@protoc_insertion_point(post_imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simian/public/proto/transfer_function.proto',
  package='simian_public.transfer_function',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+simian/public/proto/transfer_function.proto\x12\x1fsimian_public.transfer_function\"\x80\x01\n\x14TransferFunctionSpec\x12N\n\x0f\x63ontinuous_siso\x18\x01 \x01(\x0b\x32\x33.simian_public.transfer_function.ContinuousSISOSpecH\x00\x42\x18\n\x16transfer_function_type\"\x80\x03\n\x12\x43ontinuousSISOSpec\x12\x1c\n\x14numerator_polynomial\x18\x01 \x03(\x01\x12\x1e\n\x16\x64\x65nominator_polynomial\x18\x02 \x03(\x01\x12\x15\n\rinitial_state\x18\x03 \x03(\x01\x12\x18\n\x10previous_command\x18\x04 \x01(\x01\x12\x12\n\ntime_delay\x18\x05 \x01(\x01\x12n\n\x19previous_command_handling\x18\x06 \x01(\x0e\x32K.simian_public.transfer_function.ContinuousSISOSpec.PreviousCommandHandling\"w\n\x17PreviousCommandHandling\x12(\n$HOLD_FOR_DELAY_DURATION_AT_SIM_START\x10\x00\x12\x32\n.POPULATE_DELAY_DURATION_AT_SIM_START_WITH_ZERO\x10\x01\x62\x06proto3'
)



_CONTINUOUSSISOSPEC_PREVIOUSCOMMANDHANDLING = _descriptor.EnumDescriptor(
  name='PreviousCommandHandling',
  full_name='simian_public.transfer_function.ContinuousSISOSpec.PreviousCommandHandling',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HOLD_FOR_DELAY_DURATION_AT_SIM_START', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POPULATE_DELAY_DURATION_AT_SIM_START_WITH_ZERO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=477,
  serialized_end=596,
)
_sym_db.RegisterEnumDescriptor(_CONTINUOUSSISOSPEC_PREVIOUSCOMMANDHANDLING)


_TRANSFERFUNCTIONSPEC = _descriptor.Descriptor(
  name='TransferFunctionSpec',
  full_name='simian_public.transfer_function.TransferFunctionSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='continuous_siso', full_name='simian_public.transfer_function.TransferFunctionSpec.continuous_siso', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='transfer_function_type', full_name='simian_public.transfer_function.TransferFunctionSpec.transfer_function_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=81,
  serialized_end=209,
)


_CONTINUOUSSISOSPEC = _descriptor.Descriptor(
  name='ContinuousSISOSpec',
  full_name='simian_public.transfer_function.ContinuousSISOSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='numerator_polynomial', full_name='simian_public.transfer_function.ContinuousSISOSpec.numerator_polynomial', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='denominator_polynomial', full_name='simian_public.transfer_function.ContinuousSISOSpec.denominator_polynomial', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initial_state', full_name='simian_public.transfer_function.ContinuousSISOSpec.initial_state', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous_command', full_name='simian_public.transfer_function.ContinuousSISOSpec.previous_command', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_delay', full_name='simian_public.transfer_function.ContinuousSISOSpec.time_delay', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous_command_handling', full_name='simian_public.transfer_function.ContinuousSISOSpec.previous_command_handling', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTINUOUSSISOSPEC_PREVIOUSCOMMANDHANDLING,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=596,
)

_TRANSFERFUNCTIONSPEC.fields_by_name['continuous_siso'].message_type = _CONTINUOUSSISOSPEC
_TRANSFERFUNCTIONSPEC.oneofs_by_name['transfer_function_type'].fields.append(
  _TRANSFERFUNCTIONSPEC.fields_by_name['continuous_siso'])
_TRANSFERFUNCTIONSPEC.fields_by_name['continuous_siso'].containing_oneof = _TRANSFERFUNCTIONSPEC.oneofs_by_name['transfer_function_type']
_CONTINUOUSSISOSPEC.fields_by_name['previous_command_handling'].enum_type = _CONTINUOUSSISOSPEC_PREVIOUSCOMMANDHANDLING
_CONTINUOUSSISOSPEC_PREVIOUSCOMMANDHANDLING.containing_type = _CONTINUOUSSISOSPEC
DESCRIPTOR.message_types_by_name['TransferFunctionSpec'] = _TRANSFERFUNCTIONSPEC
DESCRIPTOR.message_types_by_name['ContinuousSISOSpec'] = _CONTINUOUSSISOSPEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransferFunctionSpec = _reflection.GeneratedProtocolMessageType('TransferFunctionSpec', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERFUNCTIONSPEC,
  '__module__' : 'simian.public.proto.transfer_function_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.transfer_function.TransferFunctionSpec)
  })
_sym_db.RegisterMessage(TransferFunctionSpec)

ContinuousSISOSpec = _reflection.GeneratedProtocolMessageType('ContinuousSISOSpec', (_message.Message,), {
  'DESCRIPTOR' : _CONTINUOUSSISOSPEC,
  '__module__' : 'simian.public.proto.transfer_function_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.transfer_function.ContinuousSISOSpec)
  })
_sym_db.RegisterMessage(ContinuousSISOSpec)


# @@protoc_insertion_point(module_scope)
