# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simian/public/proto/vehiclesim.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




# @@protoc_insertion_point(post_imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simian/public/proto/vehiclesim.proto',
  package='simian_public.vehiclesim',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$simian/public/proto/vehiclesim.proto\x12\x18simian_public.vehiclesim\"\x80\x02\n\x0eImportSettings\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x41\n\x04mode\x18\x02 \x01(\x0e\x32\x33.simian_public.vehiclesim.ImportSettings.ImportMode\x12\x14\n\x0cinterpolated\x18\x03 \x01(\x08\"\x85\x01\n\nImportMode\x12\x11\n\rIGNORE_IMPORT\x10\x00\x12\x0b\n\x07REPLACE\x10\x01\x12\x0e\n\nVS_REPLACE\x10\x05\x12\x07\n\x03\x41\x44\x44\x10\x02\x12\n\n\x06VS_ADD\x10\x06\x12\x0c\n\x08MULTIPLY\x10\x03\x12\x0f\n\x0bVS_MULTIPLY\x10\x07\x12\r\n\tAVAILABLE\x10\x08\"\x04\x08\x04\x10\x04\x62\x06proto3'
)



_IMPORTSETTINGS_IMPORTMODE = _descriptor.EnumDescriptor(
  name='ImportMode',
  full_name='simian_public.vehiclesim.ImportSettings.ImportMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IGNORE_IMPORT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REPLACE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VS_REPLACE', index=2, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=3, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VS_ADD', index=4, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MULTIPLY', index=5, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VS_MULTIPLY', index=6, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AVAILABLE', index=7, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=190,
  serialized_end=323,
)
_sym_db.RegisterEnumDescriptor(_IMPORTSETTINGS_IMPORTMODE)


_IMPORTSETTINGS = _descriptor.Descriptor(
  name='ImportSettings',
  full_name='simian_public.vehiclesim.ImportSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='simian_public.vehiclesim.ImportSettings.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='simian_public.vehiclesim.ImportSettings.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interpolated', full_name='simian_public.vehiclesim.ImportSettings.interpolated', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IMPORTSETTINGS_IMPORTMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=323,
)

_IMPORTSETTINGS.fields_by_name['mode'].enum_type = _IMPORTSETTINGS_IMPORTMODE
_IMPORTSETTINGS_IMPORTMODE.containing_type = _IMPORTSETTINGS
DESCRIPTOR.message_types_by_name['ImportSettings'] = _IMPORTSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImportSettings = _reflection.GeneratedProtocolMessageType('ImportSettings', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTSETTINGS,
  '__module__' : 'simian.public.proto.vehiclesim_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.vehiclesim.ImportSettings)
  })
_sym_db.RegisterMessage(ImportSettings)


# @@protoc_insertion_point(module_scope)
