# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simian/public/proto/sensor_sim/materials/lane_line_material.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from simian.public.proto.sensor_sim.materials import common_material_properties_pb2 as simian_dot_public_dot_proto_dot_sensor__sim_dot_materials_dot_common__material__properties__pb2


# @@protoc_insertion_point(post_imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simian/public/proto/sensor_sim/materials/lane_line_material.proto',
  package='simian_public.sensor_sim.materials.lane_line_material',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nAsimian/public/proto/sensor_sim/materials/lane_line_material.proto\x12\x35simian_public.sensor_sim.materials.lane_line_material\x1aIsimian/public/proto/sensor_sim/materials/common_material_properties.proto\"d\n\x1aLaneLineMaterialPresetEnum\"F\n\x16LaneLineMaterialPreset\x12\t\n\x05UNSET\x10\x00\x12\x0f\n\x0bSOLID_WHITE\x10\x01\x12\x10\n\x0cSOLID_YELLOW\x10\x02\"\xd2\x02\n\x10LaneLineMaterial\x12x\n\x06preset\x18\x01 \x01(\x0e\x32h.simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterialPresetEnum.LaneLineMaterialPreset\x12{\n\x1a\x63ommon_material_properties\x18\x02 \x01(\x0b\x32W.simian_public.sensor_sim.materials.common_material_properties.CommonMaterialProperties\x12\x17\n\x0fpaint_thickness\x18\x03 \x01(\x02\x12\x19\n\x11retroreflectivity\x18\x04 \x01(\x02\x12\x13\n\x0b\x64\x65gradation\x18\x05 \x01(\x02\x62\x06proto3'
  ,
  dependencies=[simian_dot_public_dot_proto_dot_sensor__sim_dot_materials_dot_common__material__properties__pb2.DESCRIPTOR,])



_LANELINEMATERIALPRESETENUM_LANELINEMATERIALPRESET = _descriptor.EnumDescriptor(
  name='LaneLineMaterialPreset',
  full_name='simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterialPresetEnum.LaneLineMaterialPreset',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOLID_WHITE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOLID_YELLOW', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=229,
  serialized_end=299,
)
_sym_db.RegisterEnumDescriptor(_LANELINEMATERIALPRESETENUM_LANELINEMATERIALPRESET)


_LANELINEMATERIALPRESETENUM = _descriptor.Descriptor(
  name='LaneLineMaterialPresetEnum',
  full_name='simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterialPresetEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LANELINEMATERIALPRESETENUM_LANELINEMATERIALPRESET,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=299,
)


_LANELINEMATERIAL = _descriptor.Descriptor(
  name='LaneLineMaterial',
  full_name='simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='preset', full_name='simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterial.preset', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='common_material_properties', full_name='simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterial.common_material_properties', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='paint_thickness', full_name='simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterial.paint_thickness', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retroreflectivity', full_name='simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterial.retroreflectivity', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='degradation', full_name='simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterial.degradation', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=640,
)

_LANELINEMATERIALPRESETENUM_LANELINEMATERIALPRESET.containing_type = _LANELINEMATERIALPRESETENUM
_LANELINEMATERIAL.fields_by_name['preset'].enum_type = _LANELINEMATERIALPRESETENUM_LANELINEMATERIALPRESET
_LANELINEMATERIAL.fields_by_name['common_material_properties'].message_type = simian_dot_public_dot_proto_dot_sensor__sim_dot_materials_dot_common__material__properties__pb2._COMMONMATERIALPROPERTIES
DESCRIPTOR.message_types_by_name['LaneLineMaterialPresetEnum'] = _LANELINEMATERIALPRESETENUM
DESCRIPTOR.message_types_by_name['LaneLineMaterial'] = _LANELINEMATERIAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaneLineMaterialPresetEnum = _reflection.GeneratedProtocolMessageType('LaneLineMaterialPresetEnum', (_message.Message,), {
  'DESCRIPTOR' : _LANELINEMATERIALPRESETENUM,
  '__module__' : 'simian.public.proto.sensor_sim.materials.lane_line_material_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterialPresetEnum)
  })
_sym_db.RegisterMessage(LaneLineMaterialPresetEnum)

LaneLineMaterial = _reflection.GeneratedProtocolMessageType('LaneLineMaterial', (_message.Message,), {
  'DESCRIPTOR' : _LANELINEMATERIAL,
  '__module__' : 'simian.public.proto.sensor_sim.materials.lane_line_material_pb2'
  # @@protoc_insertion_point(class_scope:simian_public.sensor_sim.materials.lane_line_material.LaneLineMaterial)
  })
_sym_db.RegisterMessage(LaneLineMaterial)


# @@protoc_insertion_point(module_scope)
